'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const canonicalMetrics = require('../assets/js/core/canonical-metrics.js');

const {
    buildFinanceClassificationContext,
    computeCanonicalFinanceMetrics,
    compareFinanceMetricSnapshots,
    validate
} = canonicalMetrics;

const DATE = '2026-07-31T08:00:00.000Z';

function tx(id, overrides = {}) {
    return {
        id,
        type: 'expense',
        category: 'Food',
        amt: 100,
        date: DATE,
        paymentSource: 'cash',
        ...overrides
    };
}

function producerFixtures() {
    return [
        tx('earned', { type: 'income', category: 'Salary', amt: 5000 }),
        tx('refund', { type: 'non_income_cash_in', category: 'Refund/Reimbursement', amt: 500 }),
        tx('cash-purchase', { category: 'Food', amt: 600 }),
        tx('card-charge', { category: 'Travel', amt: 1200, paymentSource: 'credit_card', creditCardId: 'card-1' }),
        tx('card-payment', { type: 'credit_card_payment', category: 'Aurora Rewards', amt: 800, creditCardId: 'card-1' }),
        tx('installment-payment', {
            type: 'installment_payment',
            category: 'Installments/BNPL',
            amt: 3150,
            installmentPlanId: 'plan-1',
            installmentFeeAmount: 150
        }),
        tx('debt-cash', {
            type: 'debt_increase',
            category: 'Debt to pay: Family Loan',
            amt: 10000,
            debtId: 'debt-1',
            debtBorrowTracked: true
        }),
        tx('debt-payment', {
            category: 'Debt to pay: Family Loan',
            amt: 2200,
            debtId: 'debt-1'
        }),
        tx('lent-advance', { category: 'Lent: Alex', amt: 1000, lentId: 'lent-1' }),
        tx('lent-repayment', { type: 'non_income_cash_in', category: 'Lent: Alex', amt: 400, lentId: 'lent-1' }),
        tx('savings', { category: 'Savings', amt: 700 }),
        tx('crypto-buy', {
            id: 'crypto_buy_expense_fixture',
            category: 'Investment',
            amt: 1000,
            autoGeneratedSource: 'crypto_buy',
            linkedCryptoTransactionId: 'crypto-1',
            linkedCryptoTransactionType: 'buy'
        })
    ];
}

test('canonical metric engine validates its invariants', () => {
    assert.deepEqual(validate(), { valid: true, errors: [], version: '1.0.0' });
});

test('runtime context is normalized, deduplicated, and immutable', () => {
    const context = buildFinanceClassificationContext({
        debts: [{ id: 'debt-1', name: 'Family Loan' }],
        debtIds: ['debt-1'],
        debtCategoryNames: ['Family Loan'],
        assetCategoryNames: ['Capital Equipment', 'Capital Equipment'],
        transferCategoryNames: ['Broker Transfer']
    });

    assert.deepEqual(context.debtIds, ['debt-1']);
    assert.deepEqual(context.debtCategoryNames, ['Debt to pay: Family Loan', 'Family Loan']);
    assert.deepEqual(context.assetCategoryNames, ['Capital Equipment']);
    assert.deepEqual(context.transferCategoryNames, ['Broker Transfer']);
    assert.equal(Object.isFrozen(context), true);
    assert.equal(Object.isFrozen(context.debtCategoryNames), true);
});

test('producer fixtures reconcile into orthogonal canonical metrics', () => {
    const fixtures = producerFixtures();
    const before = structuredClone(fixtures);
    const result = computeCanonicalFinanceMetrics(fixtures);

    assert.equal(result.transactionCount, 12);
    assert.equal(result.netCashFlow, 6450);
    assert.equal(result.earnedIncome, 5000);
    assert.equal(result.otherCashIn, 10900);
    assert.equal(result.consumptionSpending, 1950);
    assert.equal(result.financeChargeSpending, 150);
    assert.equal(result.settlements, 6000);
    assert.equal(result.transferDelta, -1300);
    assert.equal(result.assetAcquisitions, 1000);
    assert.equal(result.liabilityDelta, 5200);
    assert.equal(result.receivableDelta, 600);
    assert.equal(result.savingsRate, 61);
    assert.deepEqual(result.spendingByCategory, {
        Food: 600,
        Travel: 1200,
        'Installments/BNPL': 150
    });
    assert.equal(result.diagnostics.classificationCoveragePct, 100);
    assert.equal(result.diagnostics.unclassifiedCount, 0);
    assert.equal(result.diagnostics.invalidCount, 0);
    assert.equal(result.diagnostics.safeForVisibleCutover, true);
    assert.deepEqual(fixtures, before);
    assert.equal(Object.isFrozen(result), true);
});

test('legacy debt-name context classifies an unlinked repayment', () => {
    const context = buildFinanceClassificationContext({
        debts: [{ id: 'debt-1', name: 'Family Loan' }]
    });
    const result = computeCanonicalFinanceMetrics([
        tx('legacy-debt-payment', { category: 'Family Loan', amt: 900 })
    ], { context });

    assert.equal(result.classifications[0].classId, 'debt_settlement');
    assert.equal(result.netCashFlow, -900);
    assert.equal(result.consumptionSpending, 0);
    assert.equal(result.settlements, 900);
});

test('invalid dates are excluded and unknown records block cutover readiness', () => {
    const result = computeCanonicalFinanceMetrics([
        tx('bad-date', { date: '2026-02-30' }),
        tx('unknown', { type: 'mystery' })
    ], { additionalQuarantinedCount: 2 });

    assert.equal(result.transactionCount, 1);
    assert.equal(result.diagnostics.sourceTransactionCount, 2);
    assert.equal(result.diagnostics.excludedDateCount, 3);
    assert.equal(result.diagnostics.unclassifiedCount, 1);
    assert.equal(result.diagnostics.safeForVisibleCutover, false);
    assert.equal(result.diagnostics.issueCounts.unknown_type, 1);
});

test('zero earned income returns n/a-ready null savings rate', () => {
    const result = computeCanonicalFinanceMetrics([
        tx('expense-only', { amt: 250 })
    ]);
    assert.equal(result.earnedIncome, 0);
    assert.equal(result.savingsRate, null);
});

test('shadow comparison enforces cash invariance and records expected semantic changes', () => {
    const canonical = computeCanonicalFinanceMetrics(producerFixtures());
    const alignedCash = compareFinanceMetricSnapshots(canonical, {
        balance: 6450,
        income: 5000,
        nonIncomeCashIn: 10900,
        expense: 10650,
        savingsRate: -113
    });
    assert.equal(alignedCash.status, 'expected_differences');
    assert.equal(alignedCash.invariantFailures.length, 0);
    assert.equal(alignedCash.expectedDifferences.length, 2);
    assert.equal(alignedCash.readyForVisibleCutover, true);

    const brokenCash = compareFinanceMetricSnapshots(canonical, {
        balance: 6400,
        income: 5000,
        nonIncomeCashIn: 10900,
        expense: 10650,
        savingsRate: -113
    });
    assert.equal(brokenCash.status, 'invariant_failure');
    assert.equal(brokenCash.invariantFailures.length, 1);
    assert.equal(brokenCash.readyForVisibleCutover, false);
});

test('browser load order enables the gated visible metric cutover', () => {
    const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
    const classifierIndex = html.indexOf('assets/js/core/transaction-classifier.js');
    const qualityIndex = html.indexOf('assets/js/core/date-quality.js');
    const canonicalIndex = html.indexOf('assets/js/core/canonical-metrics.js');
    const legacyIndex = html.indexOf('assets/js/core/metrics.js');
    const adapterIndex = html.indexOf('assets/js/core/metric-adapter.js');
    const shadowIndex = html.indexOf('assets/js/features/metric-shadow.js');

    assert.ok(canonicalIndex > qualityIndex && qualityIndex > classifierIndex);
    assert.ok(legacyIndex > canonicalIndex);
    assert.ok(adapterIndex > legacyIndex);
    assert.ok(shadowIndex > legacyIndex);
    assert.match(html, /id="balance-label">Net Cash Flow</);
    assert.match(html, /id="overview-spending-income-label">Spending to Income</);
    assert.match(html, /id="finance-overview-attention"/);
    assert.doesNotMatch(html, /id="finance-metric-fallback-banner"/);

    const charts = fs.readFileSync(path.join(__dirname, '..', 'assets/js/ui/charts.js'), 'utf8');
    assert.match(charts, /refreshFinanceMetricShadow\(\)/);
});
