'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const statements = require('../assets/js/core/canonical-statements.js');

const {
    computeCanonicalFinanceStatementProjection,
    createFinanceStatementProvenance,
    validate
} = statements;

function tx(id, type, category, amt, overrides = {}) {
    return {
        id,
        type,
        category,
        amt,
        date: '2026-07-15',
        paymentSource: 'cash',
        ...overrides
    };
}

test('canonical statement engine validates its contract', () => {
    assert.deepEqual(validate(), { valid: true, errors: [], version: '1.0.0' });
});

test('P&L recognizes consumption but excludes principal, transfers, and asset acquisitions', () => {
    const result = computeCanonicalFinanceStatementProjection([
        tx('salary', 'income', 'Salary', 1000),
        tx('office', 'expense', 'Office Supplies', 100),
        tx('food-card', 'expense', 'Food', 200, { paymentSource: 'credit_card', creditCardId: 'card-1' }),
        tx('card-payment', 'credit_card_payment', 'Card Payments', 150, { creditCardId: 'card-1' }),
        tx('debt-payment', 'expense', 'Personal Loan', 120, {
            debtId: 'loan-1',
            debtPrincipalAmount: 100,
            debtInterestAmount: 20
        }),
        tx('savings', 'expense', 'Savings', 50),
        tx('crypto-buy', 'expense', 'Investment', 100, { autoGeneratedSource: 'crypto_buy' })
    ], {
        context: { debtIds: ['loan-1'], debtCategoryNames: ['Personal Loan'] }
    });

    assert.equal(result.pnl.income, 1000);
    assert.equal(result.pnl.costOfEarning, 100);
    assert.equal(result.pnl.operatingExpenses, 200);
    assert.equal(result.pnl.financeCosts, 20);
    assert.equal(result.pnl.ebitda, 700);
    assert.equal(result.pnl.netIncome, 680);
    assert.equal(result.pnl.debtService, 270);
    assert.equal(result.pnl.growthSpend, 150);
    assert.equal(result.cashflow.creditCardBorrowing, 200);
    assert.equal(result.cashflow.creditCardPayments, 150);
    assert.equal(result.cashflow.debtPayments, 120);
    assert.equal(result.cashflow.savingsContribution, 50);
    assert.equal(result.cashflow.assetAcquisitions, 100);
});

test('cash-flow buckets reconcile operating, investing, financing, and own-account transfers', () => {
    const result = computeCanonicalFinanceStatementProjection([
        tx('salary', 'income', 'Salary', 1000),
        tx('office', 'expense', 'Office', 100),
        tx('card-charge', 'expense', 'Food', 200, { paymentSource: 'credit_card', creditCardId: 'card-1' }),
        tx('card-payment', 'credit_card_payment', 'Card Payments', 150, { creditCardId: 'card-1' }),
        tx('debt-payment', 'expense', 'Personal Loan', 120, {
            debtId: 'loan-1',
            debtPrincipalAmount: 100,
            debtInterestAmount: 20
        }),
        tx('savings', 'expense', 'Savings', 50),
        tx('crypto-buy', 'expense', 'Investment', 100, { autoGeneratedSource: 'crypto_buy' }),
        tx('lend', 'expense', 'Lent: Alex', 30, { lentId: 'alex' }),
        tx('repay', 'income', 'Lent: Alex', 10, { lentId: 'alex' }),
        tx('asset-sale', 'non_income_cash_in', 'Asset Sale', 25, { accountingClass: 'asset_disposal' }),
        tx('borrow', 'income', 'Personal Loan', 200, { debtBorrowTracked: true }),
        tx('refund', 'non_income_cash_in', 'Refund/Reimbursement', 20),
        tx('own-transfer', 'non_income_cash_in', 'Own Transfer', 40, { isTransfer: true })
    ], {
        context: { debtIds: ['loan-1'], debtCategoryNames: ['Personal Loan'] }
    });

    assert.equal(result.cashflow.operatingCashFlow, 920);
    assert.equal(result.cashflow.investingCashFlow, -145);
    assert.equal(result.cashflow.financingCashFlow, -70);
    assert.equal(result.cashflow.transferCashFlow, 40);
    assert.equal(result.cashflow.netCashFlow, 745);
    assert.equal(result.cashflow.bucketedNetCashFlow, 745);
    assert.equal(result.cashflow.cashRecoveryIn, 30);
    assert.equal(result.cashflow.assetSaleIn, 25);
    assert.equal(result.cashflow.debtCashIn, 200);
    assert.equal(result.cashflow.ownTransferIn, 40);
    assert.equal(result.diagnostics.cashFlowDifference, 0);
    assert.equal(result.diagnostics.safeForVisibleCutover, true);
});

test('capital-like categories reach COGS only when the canonical class is consumption', () => {
    const result = computeCanonicalFinanceStatementProjection([
        tx('consumed-tools', 'expense', 'Work Tools', 80),
        tx('capital-equipment', 'expense', 'Equipment', 500, { fixedAssetId: 'asset-1' })
    ]);

    assert.equal(result.pnl.costOfEarning, 80);
    assert.equal(result.pnl.operatingExpenses, 0);
    assert.equal(result.cashflow.assetAcquisitions, 500);
    assert.equal(result.pnl.growthSpend, 500);
});

test('invalid or unknown records block visible statement cutover', () => {
    const result = computeCanonicalFinanceStatementProjection([
        tx('valid', 'income', 'Salary', 1000),
        tx('unknown', 'mystery', 'Unknown', 50)
    ]);

    assert.equal(result.diagnostics.safeForVisibleCutover, false);
    assert.equal(result.diagnostics.canonicalDiagnostics.unclassifiedCount, 1);

    const invalidDate = computeCanonicalFinanceStatementProjection([
        tx('valid', 'income', 'Salary', 1000),
        tx('bad-date', 'expense', 'Food', 50, { date: '' })
    ]);
    assert.equal(invalidDate.diagnostics.excludedTransactionCount, 1);
    assert.equal(invalidDate.diagnostics.safeForVisibleCutover, false);
});

test('statement projection and provenance are immutable', () => {
    const result = computeCanonicalFinanceStatementProjection([
        tx('salary', 'income', 'Salary', 1000)
    ]);
    const fallback = createFinanceStatementProvenance('legacy', { cutoverReason: 'test_fallback' });

    assert.equal(Object.isFrozen(result), true);
    assert.equal(Object.isFrozen(result.pnl), true);
    assert.equal(Object.isFrozen(result.cashflow), true);
    assert.equal(Object.isFrozen(result.provenance), true);
    assert.equal(fallback.engine, 'legacy');
    assert.equal(fallback.cutoverReason, 'test_fallback');
    assert.equal(Object.isFrozen(fallback), true);
});

test('browser loads canonical statement projection before Statements UI', () => {
    const financeRoot = path.join(__dirname, '..');
    const html = fs.readFileSync(path.join(financeRoot, 'index.html'), 'utf8');
    const engineIndex = html.indexOf('assets/js/core/canonical-statements.js');
    const statementsIndex = html.indexOf('assets/js/features/statements.js');

    assert.ok(engineIndex > 0);
    assert.ok(statementsIndex > engineIndex);
});

test('Statement UI and storage preserve projection provenance and new cash-flow fields', () => {
    const financeRoot = path.join(__dirname, '..');
    const ui = fs.readFileSync(path.join(financeRoot, 'assets/js/features/statements.js'), 'utf8');
    const storage = fs.readFileSync(path.join(financeRoot, 'assets/js/core/storage.js'), 'utf8');

    assert.match(ui, /statementProjectionSchemaVersion/);
    assert.match(ui, /statementProvenance/);
    assert.match(ui, /Finance Costs/);
    assert.match(ui, /Card Purchases \(Non-cash\)/);
    assert.match(ui, /finance:metric-shadow-updated/);
    assert.match(storage, /normalizeStoredStatementProvenance/);
    assert.match(storage, /financeCosts/);
    assert.match(storage, /transferCashFlow/);
    assert.match(storage, /installmentPayments/);
});
